# This is a basic workflow to help you get started with Actions

name: CI linux

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # pull_request:
    # branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: iffy/install-nim@v3
      - name: InstallLinuxDependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update && sudo apt install -y gcc npm libwebkit2gtk-4.0-dev curl python3
          
      - name: InstallMacOSDependencies
        if: runner.os == 'macOS'
        run: |
          brew install gcc python && pip install pathlib
      # Runs a set of commands using the runners shell
      - name: Test
        run: |
          nim --version
          nimble install -d -y --noSSLCheck --verbose
          nimble test
          # npm install --prefix examples/svelte
          # npm run build --prefix examples/svelte
          # npm run build --prefix examples/vue
          
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/*.exe
            build/*.dll
            build/*.a
            build/*.pyd
            build/*.so
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

       #  uses: actions/upload-artifact@v2
       #  with:
          # name: binaries
          # retention-days: 5
          # path: |
